import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import MarketplaceHeader from "@/components/MarketplaceHeader";
import MarketplaceFooter from "@/components/MarketplaceFooter";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

async function json(url: string, init?: RequestInit) { const r=await fetch(url,init);const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||"Could not complete your request.");return b; }
function Shell({children}:{children:ReactNode}){return <div className="marketplace-app min-h-screen flex flex-col"><MarketplaceHeader/><main className="flex-1 bg-muted/20 px-4 py-10"><div className="mx-auto max-w-4xl">{children}</div></main><MarketplaceFooter/></div>}

export function AuctionPage(){const {slug=""}=useParams();const [params]=useSearchParams();const [auction,setAuction]=useState<any>(null);const [form,setForm]=useState({name:"",email:"",amount:""});const [message,setMessage]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const winner=params.get("winner");
  useEffect(()=>{json(`/api/fundraising-tools/auctions/${encodeURIComponent(slug)}`).then(setAuction).catch(e=>setError(e.message));},[slug]);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{const result=winner?await json(`/api/fundraising-tools/auctions/${encodeURIComponent(slug)}/checkout`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({winnerToken:winner})}):await json(`/api/fundraising-tools/auctions/${encodeURIComponent(slug)}/bids`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,amount:Number(form.amount)})});if(result.url)window.location.assign(result.url);else{setMessage(result.message);setForm({...form,amount:String(Number(result.amount)+Number(auction.minimum_increment))});const updated=await json(`/api/fundraising-tools/auctions/${encodeURIComponent(slug)}`);setAuction(updated);}}catch(err){setError(err instanceof Error?err.message:"Could not submit.");}finally{setBusy(false);}}
  if(error&&!auction)return <Shell><Card><CardContent className="p-8 text-center"><h1 className="text-2xl font-semibold">Auction unavailable</h1><p className="mt-3 text-muted-foreground">{error}</p></CardContent></Card></Shell>;
  if(!auction)return <Shell><p className="py-10 text-center text-muted-foreground">Loading auction…</p></Shell>;
  const open=auction.status==="open"&&(!auction.starts_at||new Date(auction.starts_at)<=new Date())&&(!auction.ends_at||new Date(auction.ends_at)>new Date());const minimumBid=auction.bid_count>0?Number(auction.current_bid)+Number(auction.minimum_increment):Number(auction.starting_bid);return <Shell><Link to="/fundraising" className="text-sm underline">← Fundraising</Link><Card className="mt-5"><CardHeader><p className="market-kicker">COMMUNITY AUCTION · AUD</p><CardTitle className="text-3xl">{auction.title}</CardTitle><p className="text-sm text-muted-foreground">{auction.public_name||auction.legal_name}</p></CardHeader><CardContent className="grid gap-8 md:grid-cols-[1fr_20rem]"><section><p className="whitespace-pre-wrap leading-7">{auction.description||"Support this organisation by placing a bid."}</p><p className="mt-6 text-sm text-muted-foreground">Starting bid A${Number(auction.starting_bid).toFixed(2)} · Minimum increment A${Number(auction.minimum_increment).toFixed(2)}{auction.ends_at?` · Closes ${new Date(auction.ends_at).toLocaleString()}`:""}</p><p className="mt-2 text-sm">Bids are binding offers. The winner must complete payment within 7 days.</p></section><aside className="rounded-xl bg-muted/50 p-5"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Current bid</p><p className="mt-1 text-3xl font-bold">A${Number(auction.current_bid).toFixed(2)}</p>{auction.bid_count>0&&<p className="mt-1 text-sm text-muted-foreground">{auction.bid_count} bids</p>}{(open||winner)&&<form className="mt-5 space-y-3" onSubmit={submit}>{!winner&&<><div><Label>Your name</Label><Input required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><Label>Email</Label><Input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><Label>Bid amount (A$)</Label><Input required type="number" min={minimumBid} step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></div></>}<Button disabled={busy} className="w-full">{busy?"Please wait…":winner?"Pay winning bid":"Place bid"}</Button></form>}{message&&<p role="status" className="mt-3 text-sm text-green-800">{message}</p>}{error&&<p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}{!open&&!winner&&<p className="mt-3 text-sm text-muted-foreground">Bidding is closed.</p>}</aside></CardContent></Card></Shell>;
}

export function StorePage(){const {organisationSlug=""}=useParams();const [data,setData]=useState<any>(null);const [quantities,setQuantities]=useState<Record<number,number>>({});const [buyer,setBuyer]=useState({name:"",email:""});const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{json(`/api/fundraising-tools/stores/${encodeURIComponent(organisationSlug)}`).then(setData).catch(e=>setError(e.message));},[organisationSlug]);
  async function checkout(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const items=Object.entries(quantities).filter(([,q])=>q>0).map(([id,quantity])=>({id:Number(id),quantity}));const result=await json(`/api/fundraising-tools/stores/${encodeURIComponent(organisationSlug)}/checkout`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...buyer,items})});window.location.assign(result.url);}catch(err){setError(err instanceof Error?err.message:"Could not start checkout.");}finally{setBusy(false);}}
  const shippingSelected=Boolean(data?.products?.some((p:any)=>p.requires_shipping&&(quantities[p.id]||0)>0));
  return <Shell><Link to={`/charities/${organisationSlug}`} className="text-sm underline">← Organisation profile</Link><h1 className="mt-5 text-3xl font-bold">{data?.organisation?.public_name||data?.organisation?.legal_name||"Community store"}</h1><p className="mt-2 text-muted-foreground">Products and merchandise from this organisation.</p>{error&&<p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}{!data?<p className="py-10">Loading store…</p>:data.products.length===0?<p className="py-10 text-muted-foreground">No products are currently available.</p>:<form className="mt-6 grid gap-5 md:grid-cols-[1fr_20rem]" onSubmit={checkout}><div className="space-y-3">{data.products.map((p:any)=><Card key={p.id}><CardContent className="flex items-center justify-between gap-4 p-5"><div><h2 className="font-semibold">{p.name}</h2><p className="mt-1 text-sm text-muted-foreground">{p.description}</p><p className="mt-2 font-medium">A${Number(p.price).toFixed(2)} · {p.available} in stock</p>{p.requires_shipping&&<p className="text-xs text-muted-foreground">AU delivery · A${Number(p.shipping_fee).toFixed(2)} shipping</p>}</div><Input aria-label={`Quantity for ${p.name}`} className="w-20" type="number" min="0" max={p.available} value={quantities[p.id]||0} onChange={e=>setQuantities({...quantities,[p.id]:Number(e.target.value)})}/></CardContent></Card>)}</div><Card className="h-fit"><CardHeader><CardTitle>Checkout</CardTitle></CardHeader><CardContent className="space-y-3"><div><Label>Your name</Label><Input required value={buyer.name} onChange={e=>setBuyer({...buyer,name:e.target.value})}/></div><div><Label>Email</Label><Input required type="email" value={buyer.email} onChange={e=>setBuyer({...buyer,email:e.target.value})}/></div><p className="text-xs text-muted-foreground">Secure card checkout by Stripe.{shippingSelected?" Stripe will collect your Australian delivery address.":" Collection or delivery details will be arranged by the organisation."}</p><Button className="w-full" disabled={busy}>{busy?"Starting checkout…":"Continue to secure checkout"}</Button></CardContent></Card></form>}</Shell>;
}

export function MembershipPage(){const {organisationSlug=""}=useParams();const [data,setData]=useState<any>(null);const [form,setForm]=useState({name:"",email:""});const [error,setError]=useState("");const [busyTier,setBusyTier]=useState("");const [manageEmail,setManageEmail]=useState("");const [manageNotice,setManageNotice]=useState("");const [manageBusy,setManageBusy]=useState(false);
  useEffect(()=>{json(`/api/fundraising-tools/memberships/${encodeURIComponent(organisationSlug)}`).then(setData).catch(e=>setError(e.message));},[organisationSlug]);
  async function join(e:FormEvent,tier:any){e.preventDefault();setBusyTier(tier.slug);setError("");try{const result=await json(`/api/fundraising-tools/memberships/${encodeURIComponent(organisationSlug)}/${encodeURIComponent(tier.slug)}/checkout`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});window.location.assign(result.url);}catch(err){setError(err instanceof Error?err.message:"Could not start membership checkout.");}finally{setBusyTier("");}}
  async function requestManage(e:FormEvent){e.preventDefault();setManageBusy(true);try{const r=await fetch("/api/fundraising-tools/memberships/manage-link",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:manageEmail,organisationSlug})});const b=await r.json();if(!r.ok)throw new Error(b.message);setManageNotice(b.message);}catch(err){setManageNotice(err instanceof Error?err.message:"Could not send a management link.");}finally{setManageBusy(false);}}
  return <Shell><Link to={`/charities/${organisationSlug}`} className="text-sm underline">← Organisation profile</Link><h1 className="mt-5 text-3xl font-bold">Membership</h1><p className="mt-2 text-muted-foreground">Join {data?.organisation?.public_name||data?.organisation?.legal_name||"this organisation"} with a recurring membership.</p>{error&&<p role="alert" className="mt-4 text-sm text-destructive">{error}</p>}{!data?<p className="py-10">Loading membership options…</p>:data.tiers.length===0?<p className="py-10 text-muted-foreground">No membership tiers are currently available.</p>:<div className="mt-6 grid gap-5 md:grid-cols-2">{data.tiers.map((tier:any)=><Card key={tier.id}><CardHeader><CardTitle>{tier.name}</CardTitle><p className="text-2xl font-bold">A${Number(tier.amount).toFixed(2)}<span className="text-sm font-normal text-muted-foreground"> / {tier.billing_interval}</span></p><p className="text-sm text-muted-foreground">{tier.description}</p></CardHeader><CardContent><form className="space-y-3" onSubmit={e=>void join(e,tier)}><div><Label>Your name</Label><Input required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><Label>Email</Label><Input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><p className="text-xs text-muted-foreground">Renews {tier.billing_interval === "month" ? "monthly" : "annually"} at A${Number(tier.amount).toFixed(2)} until cancelled. Cancel online at any time.</p><Button disabled={!!busyTier}>{busyTier===tier.slug?"Opening secure checkout…":"Join and subscribe"}</Button></form></CardContent></Card>)}</div>}<Card className="mt-6"><CardHeader><CardTitle>Manage or cancel a membership</CardTitle><p className="text-sm text-muted-foreground">We’ll email a private link to the address on the membership. Cancellation stops future renewals.</p></CardHeader><CardContent><form className="flex flex-wrap gap-3" onSubmit={requestManage}><Input className="max-w-sm" type="email" required aria-label="Member email" placeholder="Email used to join" value={manageEmail} onChange={e=>setManageEmail(e.target.value)}/><Button disabled={manageBusy}>{manageBusy?"Sending…":"Email me a management link"}</Button></form>{manageNotice&&<p role="status" className="mt-3 text-sm">{manageNotice}</p>}</CardContent></Card></Shell>;
}

export function FundraisingCheckoutReturn(){const [params]=useSearchParams();const [state,setState]=useState("Checking payment status…");useEffect(()=>{const id=params.get("session_id");if(!id){setState("No payment session was supplied.");return;}let alive=true;let tries=0;const check=async()=>{try{const result=await json(`/api/fundraising-tools/checkout-status?session_id=${encodeURIComponent(id)}`);if(!alive)return;if(result.status==="paid"||result.status==="active")setState("Payment confirmed. Thank you — your receipt or membership details will be sent by email.");else if(tries++<5)setTimeout(check,2000);else setState("Payment is still processing. You can close this page; the organisation will receive confirmation from Stripe.");}catch{if(alive)setState("We could not verify this payment yet. If Stripe showed a successful payment, please check your email or contact the organisation.");}};void check();return()=>{alive=false;};},[params]);return <Shell><Card><CardContent className="p-8 text-center"><h1 className="text-2xl font-semibold">Checkout update</h1><p className="mt-3 text-muted-foreground">{state}</p><Button className="mt-5" asChild><Link to="/fundraising">Back to fundraising</Link></Button></CardContent></Card></Shell>;}

export function MembershipManagePage(){const [params]=useSearchParams();const [state,setState]=useState("");const [busy,setBusy]=useState(false);const token=params.get("token")||"";async function cancel(){setBusy(true);setState("");try{const result=await json("/api/fundraising-tools/memberships/cancel",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})});setState(result.message);}catch(error){setState(error instanceof Error?error.message:"Could not update the renewal.");}finally{setBusy(false);}}return <Shell><Card><CardHeader><CardTitle>Manage your recurring membership</CardTitle></CardHeader><CardContent><p className="text-sm text-muted-foreground">Canceling stops future renewals. Your current paid membership remains active until its renewal date.</p><Button className="mt-5" disabled={!token||busy} onClick={()=>void cancel()}>{busy?"Updating…":"Cancel future renewals"}</Button>{state&&<p role="status" className="mt-4 text-sm">{state}</p>}</CardContent></Card></Shell>;}
